package Showcase;

import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
    public static void main(String[] args) throws Exception
    {
        int port = 7999;
        ServerSocket server = new ServerSocket(port);
        Socket s = server.accept();
        // -Read the key from the file generated by the client.
        FileInputStream fis = new FileInputStream("DESKeyFile.txt");
        ObjectInputStream ois = new ObjectInputStream(fis);
        Key key = (Key) ois.readObject();
        ois.close();
        // -Use the key to decrypt the incoming message from socket s.
        Cipher decipher = Cipher.getInstance("DES");
        decipher.init(Cipher.DECRYPT_MODE, key);
        ObjectInputStream in = new ObjectInputStream(s.getInputStream());
        // -Print out the decrypt String to see if it matches the orignal message.
        int length = in.readInt();
        byte[] result = new byte[length];
        in.readFully(result);
        result = decipher.doFinal(result);
        System.out.println("The plaintext is "+new String(result));

    }
}